name: 07 - Using Expressions

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debugging information"
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
   
